version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: duddbs
      MYSQL_DATABASE: photoplace
    ports:
      - "3306:3306"
    networks:
      - app_network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
